services:
  database:
    container_name: cyblock-postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./docker/volumes/postgres-cyblock:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cy_block"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cyblock-shifting-network

  redis:
    container_name: cyblock-redis
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT:-9736}:9736
    expose:
      - 9736
    volumes:
      - ./docker/volumes/redis-cyblock:/data
    command: >
      sh -c "
      if [ -n \"$$REDIS_PASSWORD\" ]; then
        redis-server --appendonly yes --requirepass \"$$REDIS_PASSWORD\"
      else
        redis-server --appendonly yes
      fi
      "
    healthcheck:
      test: >
        sh -c "
        if [ -n \"$$REDIS_PASSWORD\" ]; then
          redis-cli -a \"$$REDIS_PASSWORD\" ping
        else
          redis-cli ping
        fi
        "
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cyblock-shifting-network

  backend:
    container_name: cyblock-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      EXTERNAL_API_BASE_URL: http://host.docker.internal:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cyblock-shifting-network

networks:
  cyblock-shifting-network:
    driver: bridge

volumes:
  data:
    name: cyblock-shifting-data